AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Globals:
  Function:
    Timeout: 3

Resources:
  UploadRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: upload_request/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        UploadRequest:
          Type: Api
          Properties:
            Path: /upload
            Method: post

Outputs:
  UploadRequestApi:
    Description: "API Gateway endpoint URL for Prod stage for Upload Request function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/upload/"
  UploadRequestFunction:
    Description: "Upload Request Lambda Function ARN"
    Value: !GetAtt UploadRequestFunction.Arn
  UploadRequestFunctionIamRole:
    Description: "Implicit IAM Role created for Upload Request function"
    Value: !GetAtt UploadRequestFunctionRole.Arn
